### ISSUE TITLE
Add backspace button hide config

### ISSUE THREAD

**Issue by dghub-founder** [Fintasys/emoji_picker_flutter#119]

**Comment by zhangzhe532** [comment]
Set null  for onBackspacePressed param
```
EmojiPicker(
    ...
    onBackspacePressed: null,
    ....
)
```

**Comment by Fintasys** [comment]
@dghub-founder Please try the current master to see if it fixes your issue
```
  emoji_picker_flutter:
    git:
      url: https://github.com/Fintasys/emoji_picker_flutter.git
      ref: master
```
