### ISSUE TITLE
Espaçamento superior interno

### ISSUE THREAD

**Issue by carlinho11** [Fintasys/emoji_picker_flutter#16]
Como faço para diminuir ou remover completamente esse espaçamento interno?

![Tela](https://user-images.githubusercontent.com/38302156/119711840-5b0ca980-be36-11eb-8f28-ac1ab1394329.PNG)

**Comment by Fintasys** [comment]
@carlinho11  There shouldn't be any space 🤔  Can you share part of your code?

**Comment by carlinho11** [comment]
Bom dia @Fintasys, 

Fiz uma simulação e ocorreu o mesmo problema:

**main.dart:**

```
import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFFf2f1f1),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(),
          ),
          _campoFigurinhas(),
        ],
      ),
    );
  }

  Widget _campoFigurinhas() {
    return Offstage(
      offstage: false,
      child: Container(
        alignment: Alignment.topCenter,
        height: 250,
        child: EmojiPicker(
          onEmojiSelected: (Category category, Emoji emoji) {},
          onBackspacePressed: () {},
          config: const Config(
              columns: 8,
              emojiSizeMax: 25.0,
              verticalSpacing: 0,
              horizontalSpacing: 0,
              initCategory: Category.RECENT,
              bgColor: Colors.white,
              indicatorColor: Color(0xff7C4EFF),
              iconColor: Colors.grey,
              iconColorSelected: Color(0xff7C4EFF),
              progressIndicatorColor: Color(0xff7C4EFF),
              backspaceColor: Color(0xff7C4EFF),
              showRecentsTab: true,
              recentsLimit: 28,
              noRecentsText: 'Não há recentes',
              noRecentsStyle: TextStyle(fontSize: 20, color: Colors.black26),
              categoryIcons: CategoryIcons(),
              buttonMode: ButtonMode.MATERIAL),
        ),
      ),
    );
  }
}
```

**pubspec.yaml:**

```
name: teste_emoti
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.5
  emoji_picker_flutter: ^1.0.5

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

Agradeço a atenção :)

**Comment by Fintasys** [comment]
I found the bug, but I don't know why. 🤔  
If you add AppBar it works.
```
Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('Emoji Picker Example App'),
      ),
```
I know how to fix it and will fix it in the next version.
Thank you for reporting the bug ! 🙇

**Comment by carlinho11** [comment]
Ótimo, estou ansioso pela próxima versão.

Agradeço a sua atenção! 😊

**Comment by Fintasys** [comment]
@carlinho11 
Can you test? Pubspec.yaml:
```
  emoji_picker_flutter:
    git:
      url: https://github.com/Fintasys/emoji_picker_flutter.git
      ref: master
```
