### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by arielt** [Fintasys/emoji_picker_flutter#53]
[!] No podspec found for `emoji_picker_flutter` in `Flutter/ephemeral/.symlinks/plugins/emoji_picker_flutter/macos`

The issue seems to be there since 1.0.9, the workaround is to revert to 1.0.8

**Comment by Fintasys** [comment]
Thank you for reporting. I could reproduce it and working on a fix 👍

**Comment by Fintasys** [comment]
@arielt I could find some issues with the platforms and missing files, thank you for reporting the issue !
I've merged a fix, you can test it by using the code below. I will try to release a new version soon.
```
  emoji_picker_flutter:
    git:
      url: https://github.com/Fintasys/emoji_picker_flutter.git
      ref: master
```
