### ISSUE TITLE
Emojis not loading in Version 1.1.2

### ISSUE THREAD

**Issue by Shaquiri1** [Fintasys/emoji_picker_flutter#65]
It only shows an infinite loading spinner :/

I tried it with the provided Example in flutter version 2.10.4

**Comment by Shaquiri1** [comment]
working in Version 1.1.1

**Comment by Paul-D-Dev** [comment]
same problem, i got an infinite loading spinner

```
environment:
  sdk: ">=2.16.1 <3.0.0"

```

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.1.2
```

- Message Console : 
`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)`
